### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unreal#27]
I've had a brief look at this project and tried following the CONTRIBUTING.md to build the project and I have a few suggestions.

Currently, the project is supposed to be checked out into an existing Unreal Engine project as a plugin. This means a developer of sentry-unreal SDK must first create a new UE project (sample), to be able to do any development. This increases the cost-of-entry for new SDK developers. Instead, I'd suggest having a look at https://github.com/getsentry/sentry-unity and think about the following changes:

* [x] move the existing contents to a new directory, e.g. what package-dev is in the Unity SDK, maybe `plugin` or `plugin-dev` is a good name? - #61 
* [x] move dependency builds to separate CI job & allow downloading for plugin developers - thus moving the binaries from the repository - #63
* [x] add script for packaging and release - #62 
* [x] add a sample project that already includes the development version of the plugin - #64 
* [ ] add a test project that includes a plugin that's ready for distribution (see also #4), which may be different than the dev version - #77

**Comment by vaind** [comment]
@tustanivsky I understand you have a demo app to simulate event captures locally? Can you maybe add the app to the `sample` now that we have moved the plugin to `plugin-dev` from the repo root?

**Comment by vaind** [comment]
it shouldn't include the plugin - ideally, we can create a symlink?

**Comment by tustanivsky** [comment]
> it shouldn't include the plugin - ideally, we can create a symlink?

I did some quick testing and it looks that UE doesn't recognize symlinks on Windows which is not good considering it's the main platform for Unreal development. On Mac it works just fine though

**Comment by vaind** [comment]
Which type of link have you tried on Windows? If you could create a PR with the sample as I can have a look around and maybe I can think of something.

**Comment by tustanivsky** [comment]
> Which type of link have you tried on Windows? If you could create a PR with the sample as is, I can have a look around and maybe I can think of something.

I've created a PR (#64) with symlink for Mac. On Windows I've tried to create one with `mklink`, but when launching the project UE doesn't detect any plugins installed
