### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unreal#300]
Subject to change and not necessarily in order:
- [x] Release Health https://github.com/getsentry/sentry-unreal/pull/270
- [x] Auto Initialization https://github.com/getsentry/sentry-unreal/pull/299
- [x] Custom Transport https://github.com/getsentry/sentry-unreal/pull/297
- [x] Update Sample to work with 5.2 https://github.com/getsentry/sentry-unreal/pull/299
- [x] Fix event level https://github.com/getsentry/sentry-unreal/issues/189
- [ ] Fix alert filter https://github.com/getsentry/sentry-unreal/issues/256
- [x] Update docs
- [x] Add the plugin to the UE Marketplace
- [x] Update CI to fail when tests fail
- [x] #332
- [ ] #378
- [ ] ...

**Comment by tustanivsky** [comment]
As far as I recall this issue was opened to track the remaining tasks for UE Marketplace publishing. Since the plugin has been already released this one can be closed.
